<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Condominio.Domain\Condominio.Domain.csproj" />
    <ProjectReference Include="..\Condominio.Infrastructure\Condominio.Infrastructure.csproj" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.Cookies" Version="2.3.12" />
    <PackageReference Include="Microsoft.AspNetCore.Components.Authorization" Version="9.0.19" />
    <PackageReference Include="Microsoft.AspNetCore.Http.Abstractions" Version="2.3.12" />
	  <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.0" />

  </ItemGroup>

</Project>
